//
// Created by akira on 04/09/22.
//

#ifndef SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_SEARCHCONTRADICTIONS_H
#define SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_SEARCHCONTRADICTIONS_H

#include "eventData.h"

struct Event;

int searchContradictions(struct Event **headerPointer);

#endif // SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_SEARCHCONTRADICTIONS_H
