//
// Created by akira on 25/08/22.
//

#ifndef SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_UNDOLOAD_H
#define SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_UNDOLOAD_H

int undoLoad(struct Event **headerPointer);

#endif // SISTEMA_DE_INTEGRACAO_DE_CONTROLE_DE_ACESSO_UNDOLOAD_H
